// 데이터(사용자 제공 그대로 사용)
  const motions = [
    {
      levels: "beginner",
      label: "덤벨 벤트오버 로우",
      labelEn: "Dumbbell Bent-Over Row",
      frames: [
        "/bodyparts/dumbbell-bentover-row/1.png",
        "/bodyparts/dumbbell-bentover-row/2.png",
        "/bodyparts/dumbbell-bentover-row/3.png",
        "/bodyparts/dumbbell-bentover-row/4.png",
      ],
      points: [
        "상체를 45~90도 숙인 상태에서 덤벨을 아래로 늘어뜨림",
        "팔꿈치를 뒤로 끌어당기며 견갑골을 강하게 수축",
        "광배근, 승모근, 능형근을 중심으로 등 전체 자극",
        "허리를 곧게 유지하며 반동 없이 수행",
      ],
      frameText: "* 등 두께 발달과 후면 체인 강화를 위한 대표적인 수평 당기기 운동.",
      setScoreText: "3 세트 10 회",
    },
    {
      levels: "beginner",
      label: "덤벨로우",
      labelEn: "Dumbbell Row",
      frames: [
        "/bodyparts/dumbbell-row/1.png",
        "/bodyparts/dumbbell-row/2.png",
      ],
      points: [
        "상체를 숙인 상태에서 덤벨을 몸 쪽으로 당기는 동작",
        "팔꿈치를 뒤로 끌어당기며 견갑골을 모아줌",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "보조로 이두근 사용",
      ],
      frameText: "* 등 두께와 등 라인을 만드는 대표적인 수평 당기기 운동.",
      setScoreText: "2 세트 15 회",
    },
    {
      levels: "beginner",
      label: "와이드 그립 풀업3",
      labelEn: "Wide Grip Pull-up3",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "3) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
    {
      levels: "beginner",
      label: "와이드 그립 풀업33",
      labelEn: "Wide Grip Pull-up3",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "33) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
    {
      levels: "intermediate",
      label: "와이드 그립 풀업4",
      labelEn: "Wide Grip Pull-up4",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "4) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
    {
      levels: "intermediate",
      label: "와이드 그립 풀업5",
      labelEn: "Wide Grip Pull-up5",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "5) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
    {
      levels: "intermediate",
      label: "와이드 그립 풀업6",
      labelEn: "Wide Grip Pull-up6",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "6) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
    {
      levels: "advanced",
      label: "와이드 그립 풀업7",
      labelEn: "Wide Grip Pull-up7",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "7) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
    {
      levels: "advanced",
      label: "와이드 그립 풀업8",
      labelEn: "Wide Grip Pull-up8",
      frames: [
        "/bodyparts/pull-up/1.png",
        "/bodyparts/pull-up/2.png",
        "/bodyparts/pull-up/3.png",
        "/bodyparts/pull-up/4.png",
      ],
      points: [
        "손바닥이 바깥쪽(오버그립)으로 바를 잡고 있음",
        "턱이 바 위까지 올라가는 동작",
        "광배근(등 하부), 승모근, 능형근이 주 타겟",
        "8) 보조로 이두근 사용",
      ],
      frameText: "* 등(광배/승모/능형) 타겟. 반동 없이 천천히.",
      setScoreText: "3 * 10",
    },
  ] as const;